apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: test
spec:
  disks:
    - device: /dev/vda 
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: test
        ip:
          address: 192.168.254.101
          netmask: 255.255.255.0
          gateway: 192.168.254.1
        lease_time: 86400
        mac: 52:54:00:ff:54:38
        name_servers:
          - 1.1.1.1
          - 8.8.8.8
        uefi: false
      netboot:
        allowPXE: true
        allowWorkflow: true