---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-oraclelinux-93
spec:
  template:
    spec:
      containers:
        - name: download-oraclelinux
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              "https://yum.oracle.com/templates/OracleLinux/OL9/u5/x86_64/OL9U5_x86_64-kvm-b259.qcow2",
              "/output",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: /opt/hook
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-image
