---
apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: oraclelinux-95
spec:
  data: |
    version: "0.1"
    name: oraclelinux-95
    global_timeout: 1800
    tasks:
      - name: "os installation"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: Stream Oracle Linux 9.5 image
            image: quay.io/tinkerbell/actions/image2disk:latest
            timeout: 600
            environment:
              DEST_DISK: {{ index .Hardware.Disks 0 }}
              IMG_URL: "http://192.168.254.251:8080/OL9U5_x86_64-kvm-b259.raw.gz"
              COMPRESSED: true
          - name: activate lvm volume group
            image: oraclelinux:9
            timeout: 600
            pid: host
            command: [ "sh", "-c", "dnf install -y lvm2 && vgscan --mknodes && vgchange -ay && dmsetup mknodes" ]
          - name: add cloud-init config
            image: quay.io/tinkerbell/actions/writefile:latest
            timeout: 90
            environment:
              CONTENTS: |
                datasource:
                  Ec2:
                    metadata_urls: ["http://192.168.254.201:50061"]
                    strict_id: false
                manage_etc_hosts: localhost
                warnings:
                  dsid_missing_source: off      
              DEST_DISK: /dev/mapper/vg_main-lv_root
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              DIRMODE: "0700"
              FS_TYPE: xfs
              GID: "0"
              MODE: "0600"
              UID: "0"
          - name: "add cloud-init ds-identity"
            image: quay.io/tinkerbell/actions/writefile:latest
            timeout: 90
            environment:
              DEST_DISK: /dev/mapper/vg_main-lv_root
              FS_TYPE: xfs
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: Ec2
          # - name: "kexec into os"
          #   image: ghcr.io/jacobweinstock/waitdaemon:latest
          #   timeout: 180
          #   pid: host
          #   environment:
          #     BLOCK_DEVICE: /dev/mapper/vg_main-lv_root
          #     FS_TYPE: xfs
          #     IMAGE: quay.io/tinkerbell/actions/kexec:latest
          #     WAIT_SECONDS: 10
          #     GRUBCFG_PATH: /boot/grub2/grub.cfg
          #   volumes:
          #     - /var/run/docker.sock:/var/run/docker.sock