---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-almalinux-180
spec:
  template:
    spec:
      containers:
        - name: download-alma
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              "https://raw.repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-8.10-20240819.x86_64.qcow2",
              "/output",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: /opt/hook
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-image
